language: cpp
before_script:
  - sudo apt-get install pandoc
script:
 - ./slides/check_slides.sh # check lectures
 - ./slides/gen_slides.sh # render HTML slides using Pandoc
notifications:
  email: false
